server:
  port: 9090

spring:
  application:
    name: job-management
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    database: h2
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: true
      hibernate.generate_statistics: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
  jackson:
    default-property-inclusion: non_null
  mvc:
    favicon:
      enabled: false
  task:
    execution:
      thread-name-prefix: payment-task-
      pool:
        core-size: 10
        max-size: 100
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: payment-scheduling-
      pool:
        size: 2
